name: OCaml CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build_and_test:
    runs-on: ubuntu-22.04

    container:
      image: ocaml/opam:ubuntu-22.04-ocaml-5.1

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # GitHub иногда ругается на "dubious ownership" внутри контейнера
      - name: Mark workspace as safe
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Update opam repository
        run: opam update -y

      - name: Install dependencies (including test deps)
        run: opam install . --deps-only --with-test -y

      - name: Build
        run: opam exec -- dune build

      - name: Test
        run: opam exec -- dune runtest
