name: OCaml CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build_and_test:
    runs-on: ubuntu-22.04

    container:
      image: ocaml/opam:ubuntu-22.04-ocaml-5.1
      options: --user 0

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fix permissions
        run: |
          chown -R opam:opam "$GITHUB_WORKSPACE"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Update opam repo
        run: |
          su - opam -c "opam update -y"

      - name: Install deps
        run: |
          su - opam -c "opam install . --deps-only --with-test -y"

      - name: Build
        run: |
          su - opam -c "opam exec -- dune build"

      - name: Test
        run: |
          su - opam -c "opam exec -- dune runtest"
